// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.A365.Observability.Runtime.Tracing.Contracts.Messages
{
    /// <summary>
    /// Represents the list of input messages sent to the model.
    /// Serializes as a plain JSON array per OTel gen-ai semantic conventions.
    /// </summary>
    [JsonConverter(typeof(InputMessagesConverter))]
    public sealed class InputMessages
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InputMessages"/> class.
        /// </summary>
        /// <param name="messages">The input chat messages.</param>
        public InputMessages(IReadOnlyList<ChatMessage> messages)
        {
            Messages = messages ?? throw new ArgumentNullException(nameof(messages));
        }

        /// <summary>Gets the input chat messages.</summary>
        public IReadOnlyList<ChatMessage> Messages { get; }
    }

    /// <summary>
    /// Represents the list of output messages generated by the model.
    /// Serializes as a plain JSON array per OTel gen-ai semantic conventions.
    /// </summary>
    [JsonConverter(typeof(OutputMessagesConverter))]
    public sealed class OutputMessages
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutputMessages"/> class.
        /// </summary>
        /// <param name="messages">The output messages.</param>
        public OutputMessages(IReadOnlyList<OutputMessage> messages)
        {
            Messages = messages ?? throw new ArgumentNullException(nameof(messages));
        }

        /// <summary>Gets the output messages.</summary>
        public IReadOnlyList<OutputMessage> Messages { get; }
    }

    /// <summary>
    /// Serializes <see cref="InputMessages"/> as a plain JSON array of ChatMessage objects.
    /// </summary>
    internal sealed class InputMessagesConverter : JsonConverter<InputMessages>
    {
        /// <inheritdoc/>
        public override InputMessages Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            throw new NotSupportedException("Deserialization of InputMessages is not supported.");
        }

        /// <inheritdoc/>
        public override void Write(Utf8JsonWriter writer, InputMessages value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value.Messages, options);
        }
    }

    /// <summary>
    /// Serializes <see cref="OutputMessages"/> as a plain JSON array of OutputMessage objects.
    /// </summary>
    internal sealed class OutputMessagesConverter : JsonConverter<OutputMessages>
    {
        /// <inheritdoc/>
        public override OutputMessages Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            throw new NotSupportedException("Deserialization of OutputMessages is not supported.");
        }

        /// <inheritdoc/>
        public override void Write(Utf8JsonWriter writer, OutputMessages value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value.Messages, options);
        }
    }
}
