<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <DistroSmokePackageVersion Condition="'$(DistroSmokePackageVersion)' == ''">$(MicrosoftOpenTelemetryPackageVersion)</DistroSmokePackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.OpenTelemetry" Version="[$(DistroSmokePackageVersion)]" />
  </ItemGroup>
</Project>
